blogger_blog_homepage:
    path:     /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    requirements:
         methods:  GET
blogger_blog_about:
    path:     /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    requirements:
         methods:  GET
blogger_blog_contact:
    path:  /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }
    requirements:
         methods:  GET|POST